server:
  port: 15188
  servlet:
    context-path: /api
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/ywym?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
    username: root
    password: root
mybatis:
  mapper-locations:
    - classpath:dao/*.xml
    - classpath*:com/**/mapper/*.xml
wx:
  miniapp:
    configs:
      - appid: wx1d6bd9d816529dc9 #微信小程序的appid
        secret: 86964ac75d63e548f3290a0cbc12e4fb #微信小程序的Secret
        token: #微信小程序消息服务器配置的token
        aesKey: #微信小程序消息服务器配置的EncodingAESKey
        msgDataFormat: JSON
jwt:
    tokenHeader: Authorization #JWT存储的请求头
    secret: hackerff.code.ywym #JWT加解密使用的密钥
    expiration: 604800 #JWT的超期限时间(60*60*24*7)
    tokenHead: 'Bearer '  #JWT负载中拿到开头

secure:
    ignored:
        urls: #安全路径白名单
          - /swagger-ui.html
          - /swagger-resources/**
          - /swagger/**
          - /**/v2/api-docs
          - /**/*.js
          - /**/*.css
          - /**/*.png
          - /**/*.ico
          - /wx/user/*/login
