server:
  port: 15189
  servlet:
    context-path: /company
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/ywym?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai&zeroDateTimeBehavior=convertToNull
    username: root
    password: root
mybatis:
  mapper-locations:
    - classpath:dao/*.xml
    - classpath*:com/**/mapper/*.xml
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
jwt:
  tokenHeader: Authorization #JWT存储的请求头
  secret: hackerff.code.ywym #JWT加解密使用的密钥
  expiration: 604800 #JWT的超期限时间(60*60*24*7)
  tokenHead: 'Bearer '  #JWT负载中拿到开头
secure:
    ignored:
        urls: #安全路径白名单
          - /swagger-ui.html
          - /swagger-resources/**
          - /swagger/**
          - /**/v2/api-docs
          - /**/*.js
          - /**/*.css
          - /**/*.png
          - /**/*.ico
          - /wx/user/*/login
          - /**
